config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'pages/info'
  
  resources :comments
  resources :interests
  resources :ideas
  resources :events
  get 'welcome/index'

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% if not user_signed_in? %>
<!-- <!DOCTYPE html>
<html>
<head>
  <title>FlockR</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">FlockR: Flock togetheR</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/interests">Interests</a></li>
      </ul>
      <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
    </div>
  </div>
</nav>

<div class="container">
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
  <%= yield %>
</div>
<footer>
  <div class="container">
    FlockR 2015
  </div>
</footer>

</body>
</html>
 -->


<html lang="en">

<body id="page-top">
    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1>Flock together with people of similar interests!</h1>
                <hr>
                <p><font color="#000000">Attend events that align with your interests and meet others who have similar passions.</font></p>
                <!-- <a href="#about" class="btn btn-primary btn-xl page-scroll">Login Here!</a> -->
                <%= link_to "Login Here!", new_user_session_path, :class => 'btn btn-primary btn-xl page-scroll' %>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
      <body style="background-color:white;">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Don't have an account?</h2>
                    <hr class="light">
                    <p class="text-faded">Create an account to see which events are happening near you!</p>
                    <!-- <a href="#" class="btn btn-default btn-xl">Sign Up</a> -->
                    <%= link_to "Sign Up", new_user_registration_path, :class => 'btn btn-default btn-xl' %>
                </div>
            </div>
        </div>
      </body>
    </section>

    <section id="contact">
        <div class="container">
            <head>
              <title>Flockr</title>
              <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
              <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
              <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
              <%= csrf_meta_tags %>
            </head>
            <body>

            <div class="container">
              <% if notice %>
                <p class="alert alert-success"><%= notice %></p>
              <% end %>
              <% if alert %>
                <p class="alert alert-danger"><%= alert %></p>
              <% end %>
              <%= yield %>
            </div>

            </body>
        </div>
    </section>

    <!-- jQuery -->
    <%= stylesheet_link_tag "application.js" %>
    <script src="../../../assets/javascripts/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../../../assets/javascripts//bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="../../../assets/javascripts//jquery.easing.min.js"></script>
    <script src="../../../assets/javascripts//jquery.fittext.js"></script>
    <script src="../../../assets/javascripts//wow.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../../../assets/javascripts//creative.js"></script>

</body>

<% else %>


<section class="bg-primary" id="about">
      <body style="background-color:white;">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Select an option</h2>
                    <hr class="light">
                    <!-- <a href="#" class="btn btn-default btn-xl">Sign Up</a> -->
                    <%= link_to "add an interest", new_interest_path, :class => 'btn btn-default btn-xl' %>
                    <%= link_to "create an event", new_event_path, :class => 'btn btn-default btn-xl' %>
                    <%= link_to "upcoming events", events_path, :class => 'btn btn-default btn-xl' %>
                    
                </div>
            </div>
        </div>
      </body>
    </section>


<% end %>