config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'pages/info'
  
  resources :comments
  resources :interests
  resources :ideas
  resources :events
  get 'welcome/index'

  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
    validates :address, presence: true
    has_many :comments
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find_by_id(params[:id])
      @comments = @event.comments.all
      @comment = @event.comments.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:address, :latitude, :longitude, :title, :description, :time, :date)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <br>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, :size=>"50" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time, {:ampm => true, :minute_step => 15} %>
  </div>
  <br>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date, :order => [:day, :month, :year] %>
    
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div align='center'>
  <h1>Editing Event</h1>
 </div>

<div class="container bs-docs-container">
  <div class="row">
	<div class="col-md-9" role="main">
	  <%= render 'form' %>

      <%= link_to 'Show', @event %> |
	  <%= link_to 'Back', events_path %>
	</div>
  </div>
</div>

app/views/events/index.html.erb
<div align='center'>
  <h1>Upcoming Events</h1>
</div>

<div class="container bs-docs-container">
  <div class="row">
    <div class="col-md-9" role="main">
      <% @events.first(10).each do |event| %>
        <h3>
          <strong> <%= link_to event.title, event %> </strong>
        </h3>

        <p>
          <%= event.date.strftime("%B %d, %Y")  %>
          <%= event.time.strftime("%I:%M %p") %>
        </p>  

        <p>
          <%= event.address %>
        </p>

        <p>
          Description: <%= event.description %>
        </p>
      <% end %>

      <%= link_to 'New Event', new_event_path %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div align='center'>
  <h1>New Event</h1>
</div>


<div class="container bs-docs-container">
  <div class="row">
	<div class="col-md-9" role="main">
	  <%= render 'form' %>

	  <br>
	  <%= link_to 'Back', events_path %>
	</div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container bs-docs-container">
<div class="row">
<div class="col-md-9" role="main">
<h3>
  <strong> <%= @event.title %> </strong>
</h3>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time.strftime("%I:%M %p") %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date.strftime("%B %d, %Y")  %>
</p>

<p>
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@event.latitude}%2C#{@event.longitude}" %>
</p>

<h3>Comments</h3>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user_name %></strong>
    <br />
    <p><%= comment.body %></p>
    <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
  <br>
<% end %>
<%= render 'comments/form' %>

<br>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>
</div>
</div>
</div>