config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'pages/info'
  
  resources :comments
  resources :interests
  resources :ideas
  resources :events
  get 'welcome/index'

  root 'welcome#index'

end

app/models/interest.rb
class Interest < ActiveRecord::Base
    mount_uploader :picture, PictureUploader
    validates :name, presence: true
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :set_interest, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /interests
  # GET /interests.json
  def index
    @interests = Interest.all
  end

  # GET /interests/1
  # GET /interests/1.json
  def show
  end

  # GET /interests/new
  def new
    @interest = Interest.new
  end

  # GET /interests/1/edit
  def edit
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(interest_params)

    respond_to do |format|
      if @interest.save
        format.html { redirect_to @interest, notice: 'Interest was successfully created.' }
        format.json { render :show, status: :created, location: @interest }
      else
        format.html { render :new }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interests/1
  # PATCH/PUT /interests/1.json
  def update
    respond_to do |format|
      if @interest.update(interest_params)
        format.html { redirect_to @interest, notice: 'Interest was successfully updated.' }
        format.json { render :show, status: :ok, location: @interest }
      else
        format.html { render :edit }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.json
  def destroy
    @interest.destroy
    respond_to do |format|
      format.html { redirect_to interests_url, notice: 'Interest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interest
      @interest = Interest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interest_params
      params.require(:interest).permit(:name, :description, :picture)
    end
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/interests/_form.html.erb
<%= form_for @interest, :html => {:multipart => true} do |f| %>
  <% if @interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interest.errors.count, "error") %> prohibited this interest from being saved:</h2>

      <ul>
      <% @interest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <br>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interests/edit.html.erb
<h1>Editing Interest</h1>

<div class="container bs-docs-container">
  <div class="row">
	<div class="col-md-9" role="main">
	  <%= render 'form' %>

	  <%= link_to 'Show', @interest %> |
	  <%= link_to 'Back', interests_path %>
	</div>
  </div>
</div>

app/views/interests/index.html.erb
<p id="notice"><%= notice %></p>

<div align='center'>
  <h1>Listing Interests</h1>
</div>

<div class="container bs-docs-container">
  <div class="row">
    <div class="col-md-9" role="main">
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Picture</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @interests.each do |interest| %>
            <tr>
              <td><%= interest.name %></td>
              <td><%= interest.description %></td>
              <td><%= interest.picture %></td>
              <td><%= link_to 'Show', interest %></td>
              <td><%= link_to 'Edit', edit_interest_path(interest) %></td>
              <td><%= link_to 'Destroy', interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Interest', new_interest_path %>
    </div>
  </div>
</div>

app/views/interests/new.html.erb
<div align='center'>
  <h1>New Interest</h1>
</div>

<div class="container bs-docs-container">
  <div class="row">
    <div class="col-md-9" role="main">
	  <%= render 'form' %>

	  <br>
	  <%= link_to 'Back', interests_path %>
    </div>
  </div>
</div>

app/views/interests/show.html.erb
<div class="container bs-docs-container">
<div class="row">
<div class="col-md-9" role="main">
<p>
  <strong>Name:</strong>
  <%= @interest.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @interest.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@interest.picture_url, :width => 600) if @interest.picture.present? %>
</p>

<%= link_to 'Edit', edit_interest_path(@interest) %> |
<%= link_to 'Back', interests_path %>
</div>
</div>
</div>